name: CI (Regress-Tests)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests (headless Chrome)
        run: |
          mvn -B -e -Dselenide.browser=chrome -Dselenide.headless=true clean test

      - name: Upload test reports (Surefire, Allure, Selenide)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/**
            target/failsafe-reports/**
            target/allure-results/**
            build/reports/tests/**
            selenide-*/**
          if-no-files-found: ignore
